# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: vector_service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'vector_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14vector_service.proto\x12\x0evector_service\"+\n\rVectorMessage\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x0e\n\x06values\x18\x02 \x03(\x02\"1\n\x0eIngestResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\"3\n\x0cQueryRequest\x12\x14\n\x0cquery_vector\x18\x01 \x03(\x02\x12\r\n\x05top_k\x18\x02 \x01(\x05\"+\n\x0bSearchMatch\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x10\n\x08\x64istance\x18\x02 \x01(\x02\"M\n\rQueryResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12,\n\x07matches\x18\x02 \x03(\x0b\x32\x1b.vector_service.SearchMatch2\xc0\x01\n\x13VectorComputeEngine\x12S\n\x12IngestVectorStream\x12\x1d.vector_service.VectorMessage\x1a\x1e.vector_service.IngestResponse\x12T\n\x15QueryNearestNeighbors\x12\x1c.vector_service.QueryRequest\x1a\x1d.vector_service.QueryResponseB\x1a\n\x16\x63om.search.engine.grpcP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'vector_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\026com.search.engine.grpcP\001'
  _globals['_VECTORMESSAGE']._serialized_start=40
  _globals['_VECTORMESSAGE']._serialized_end=83
  _globals['_INGESTRESPONSE']._serialized_start=85
  _globals['_INGESTRESPONSE']._serialized_end=134
  _globals['_QUERYREQUEST']._serialized_start=136
  _globals['_QUERYREQUEST']._serialized_end=187
  _globals['_SEARCHMATCH']._serialized_start=189
  _globals['_SEARCHMATCH']._serialized_end=232
  _globals['_QUERYRESPONSE']._serialized_start=234
  _globals['_QUERYRESPONSE']._serialized_end=311
  _globals['_VECTORCOMPUTEENGINE']._serialized_start=314
  _globals['_VECTORCOMPUTEENGINE']._serialized_end=506
# @@protoc_insertion_point(module_scope)
